// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Streams")]
[assembly: AssemblyProductAttribute("Streams")]
[assembly: AssemblyCompanyAttribute("Nessos Information Technologies")]
[assembly: AssemblyVersionAttribute("0.2.6")]
[assembly: AssemblyFileVersionAttribute("0.2.6")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.2.6";
    }
}
