// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Streams")]
[assembly: AssemblyProductAttribute("Streams")]
[assembly: AssemblyCompanyAttribute("Nessos Information Technologies")]
[assembly: AssemblyCopyrightAttribute("© Nessos Information Technologies.")]
[assembly: AssemblyTrademarkAttribute("MBrace")]
[assembly: AssemblyVersionAttribute("0.5.0")]
[assembly: AssemblyFileVersionAttribute("0.5.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Streams";
        internal const System.String AssemblyProduct = "Streams";
        internal const System.String AssemblyCompany = "Nessos Information Technologies";
        internal const System.String AssemblyCopyright = "© Nessos Information Technologies.";
        internal const System.String AssemblyTrademark = "MBrace";
        internal const System.String AssemblyVersion = "0.5.0";
        internal const System.String AssemblyFileVersion = "0.5.0";
    }
}
