// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Streams")>]
[<assembly: AssemblyProductAttribute("Streams")>]
[<assembly: AssemblyCompanyAttribute("Nessos Information Technologies")>]
[<assembly: AssemblyCopyrightAttribute("© Nessos Information Technologies.")>]
[<assembly: AssemblyTrademarkAttribute("MBrace")>]
[<assembly: AssemblyVersionAttribute("0.5.0")>]
[<assembly: AssemblyFileVersionAttribute("0.5.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Streams"
    let [<Literal>] AssemblyProduct = "Streams"
    let [<Literal>] AssemblyCompany = "Nessos Information Technologies"
    let [<Literal>] AssemblyCopyright = "© Nessos Information Technologies."
    let [<Literal>] AssemblyTrademark = "MBrace"
    let [<Literal>] AssemblyVersion = "0.5.0"
    let [<Literal>] AssemblyFileVersion = "0.5.0"
